name: decisions
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Static
      fonts:
        - asset: assets/PressStart2P-Regular.ttf

  uses-material-design: true

  # Add this section to declare the assets
  assets:
    - assets/WhatsApp_icon.png
    - assets/Telegram_icon.png
    - assets/mail.png
    - assets/imessage.png
    - assets/homepage.png
    - assets/darttitle.png
    - assets/dartbackground.png
    - assets/title.png
    - assets/create_room2.png
    - assets/join_room2.png
    - assets/random.png
